name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Clean & Build package
        run: |
          rm -rf node_modules
          yarn install
          yarn prepare

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Clean & Build Android
        run: |
          rm -rf node_modules
          rm -rf ~/.gradle
          yarn install
          yarn react-native generate-specs || echo "No codegen step needed"
          cd example/android
          ./gradlew clean
          cd ../..
          yarn android

  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Clean & Build iOS
        run: |
          rm -rf node_modules
          rm -rf example/ios/Pods
          rm -rf example/ios/build
          rm -rf ~/Library/Developer/Xcode/DerivedData
          yarn install
          yarn react-native generate-specs || echo "No codegen step needed"
          cd example/ios
          pod install --repo-update
          cd ../..
          yarn ios
